---
title: "eds212-day2-tasks"
format: html
editor: visual
---

# Derivatives in R

## Create a new version-controlled R Project

```{r}
library(tidyverse)
library(palmerpenguins)
usethis::use_git()
usethis::use_github()
```

# Find Derivatives using R 

```{r}

fx <- expression(x^2)
fx_dx <- D(expr = expression(x^2), name = "x")
fx_dx
 
x <- 3 

eval(fx_dx)

pa <- expression(2(3*a+2)^4 - 5)
pa_da <- D(expr = expression(2*(3*a+2)^4 - 5), name = "a")
pa_da
 
a <- 1.2

eval(pa_da)

```

# Section 4: Make another penguin plot. Bill Length vs Bill Depth 

```{r}
library(ggplot2)
ggplot(data = penguins, aes(x =bill_len, y = bill_dep ))+ 
  geom_point(aes(color = species)) + 
   scale_color_manual(values = c("darkorange", "purple", "cyan"))+ 
  labs(x = "Bill Length (cm)", 
       y = "Bill Depth (cm)", 
       title = "Palmer Penguins Bill Size measurements", 
       subtitle = "Palmer Archipelago, Antarctica (2007-2009)", 
       caption = "Collected by Dr. Kristen Gorman") + 
  theme_minimal()
```

# Jitter Plot of Flipper Length

```{r}
library(ggplot2)
ggplot(data = penguins, aes(x =species, y = flipper_len ))+ 
  geom_jitter(aes(color = species)) + 
   scale_color_manual(values = c("darkorange", "purple", "cyan"))+ 
  labs(x = "Species", 
       y = "Flipper Length (cm)", 
       title = "Palmer Penguins Flipper Length by Species ", 
       subtitle = "Palmer Archipelago, Antarctica (2007-2009)", 
       caption = "Collected by Dr. Kristen Gorman") + 
  theme_minimal()
```
